version: '3.1'
services:
    sonar:
        image: owasp/sonarqube
        container_name: sonar
        depends_on: 
          - db_sonar
        expose:
          - "9000"
          - "9092"
        restart: unless-stopped
        environment:
          - SONARQUBE_JDBC_USERNAME=ranos
          - SONARQUBE_JDBC_PASSWORD=ebuq
          - SONARQUBE_JDBC_URL=jdbc:postgresql://db_sonar:5432/qube
        volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
        networks:
            - services
    db_sonar:
        image: postgres
        container_name: dbs
        expose:
          - "5432"
        volumes:
          - postgresql:/var/lib/postgresql
          - postgresql_data:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
          - POSTGRES_USER=ranos
          - POSTGRES_PASSWORD=ebuq
          - POSTGRES_DB=qube
        networks:
            - services
    jenkins:
      container_name: jenkins
      build:
        context: .
        dockerfile: Dockerfile.jenkins
      restart: always
      hostname: 'jenkins'
      expose:
        - '8080'
        - '50000'
      volumes:
        - 'jenkins_home:/var/jenkins_home'
        - '/var/run/docker.sock:/var/run/docker.sock'
      networks:
            - services
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      container_name: gitlab
      restart: always
      hostname: 'gitlab'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://localhost:8000'
      expose:
        - '8000'
        - '8443'
        - '23'
      volumes:
        - 'gitlab-config:/etc/gitlab'
        - 'gitlab-logs:/var/log/gitlab'
        - 'gitlab-data:/var/opt/gitlab'
      networks:
            - services
    reverseproxy:
        image:  nginx:latest
        container_name: proxy_nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/nginx/:/etc/nginx/:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - services
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins_home:
networks:
    services:
        external:
          name: services
